### ISSUE TITLE
add web back end that ide50 and compare50 can use

### ISSUE THREAD

**Issue by dmalan** [cs50/render50#44]

**Comment by NagariaHussain** [comment]
Ya, I was thinking exactly that after watching you in twitch stream sir. I was thinking to make a flask web app which let's the user to select a ".py" file, as a starting point and then starts downloading the generated pdf. What do you think? I am stuck around deploying this.

**Comment by NagariaHussain** [comment]
I implemented a starter front end website, can you please check it out, [https://codetopdf.hussainnagaria.com](url) and backend can be found on my github repository render50Web. Thanks in advance!
