### ISSUE TITLE
Bengali Text Support in the source code, at least inside string!

### ISSUE THREAD

**Issue by ehzawad** [cs50/render50#92]
![IMG_0445](https://github.com/cs50/render50/assets/12381692/5d9adc60-f18e-4838-9d8b-cfc08e0864f8)
Not sure if it's a bug, but after converting source codes into pdfs, apparently all my Bengali (বাংলা) text turn out EMPTY! Is there any workaround for this? Like Am I missing some LaTex packages or something? I'm honestly not sure! If possible, suggest me some pointers so that I could figure something out!

Here is another screenshot! 
![IMG_0446](https://github.com/cs50/render50/assets/12381692/41e62f07-bbc5-4f60-bfad-a950d795223d)

**Comment by dmalan** [comment]
Did you generate that PDF at https://render.cs50.io/, in https://cs50.dev/, or on your own machine? (Do paste some sample source code here, too, so we can test!)

**Comment by ehzawad** [comment]
Locally, on my own machine (WSL2, Ubuntu 22.04.4) windows 11! Actually I tried it on [render50](https://render.cs50.io/), but as my project has too many files, it failed. Anyway, to help you debug the problem, I have attached a few source files which has **Bengali text** within. Usually it renders all the Bengali text as empty!
![Screenshot 2024-05-14 132716](https://github.com/cs50/render50/assets/12381692/b2554a1c-dcb3-45a3-ba4a-d86094d7fb2e)

[cs50rendertest.zip](https://github.com/cs50/render50/files/15304728/cs50rendertest.zip)

**Comment by dmalan** [comment]
On your own machine, `sudo apt update && sudo apt install -y fonts-beng-extra` should fix!

Mind also sending a complete Zip file, with all your files, to sysadmins@cs50.harvard.edu so we can see why https://render.cs50.io/ fails?
